# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RACDemo' do
use_frameworks!
    pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
   	pod 'Masonry'

end

target 'RACDemoTests' do

end

