# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RACDemo' do
    pod 'ReactiveCocoa' , '2.5'
   	pod 'Masonry'
use_frameworks!
end

target 'RACDemoTests' do

end

